using BC.ACCOUNTING.APPLICATION.Interfaces.SaleListing;
using BC.ACCOUNTING.CORE.DTO.SaleListing;
using BC.ACCOUNTING.CORE.Entities;
using BC.ACCOUNTING.INFRASTRUCTURE.DBAccess;

namespace BC.ACCOUNTING.INFRASTRUCTURE.Repository.SaleListing
{
    public class SaleListingRepository : ISaleListingRepository
    {
        private readonly ISqlDataAccess _sqlDataAccess;

        public SaleListingRepository(ISqlDataAccess sqlDataAccess)
        {
            _sqlDataAccess = sqlDataAccess;
        }

        public async Task<List<SaleListingModel>> GetSaleListingsAsync(SaleListingDto dto)
        {
            var conditionByDate = string.Empty;
            var condition = string.Empty;
            if (string.IsNullOrEmpty(dto.AnalM3))
            {
                condition = string.Empty;
            }
            else
            {
                condition = $" AND D.ANAL_M3 = '{dto.AnalM3}'";
            }

            if (string.IsNullOrEmpty(dto.Date1) && string.IsNullOrEmpty(dto.Date2))
            {
                conditionByDate = " AND H.INV_PRD BETWEEN @PRD_1 AND @PRD_2";
            }
            else
            {
                conditionByDate = " AND H.TRANS_DATE BETWEEN @DATE1 AND @DATE2";
            }
            var sql = $@"SELECT H.TRANS_REF [HeaderTransactionRef],H.QUOTATION_REF HeaderQuotationNumber, D.INV_NO HeaderInvoiceNumber, 
CONVERT(DATE,H.TRANS_DATE) [HeaderTransactionDate], H.TRANS_CODE [HeaderTransactionCode], H.ORDER_NO [HeaderSaleOrderNo],
H.PRN_DATE [HeaderPrintOrderDate], H.ORDER_DATE [HeaderSaleOrderDate], H.DEL_DATE [HeaderDeliveryDate], 
CONVERT(DATE,H.INV_DATE) [HeaderInvoiceDate], H.INV_PRD [HeaderInvoicePeriod], H.CUST_REF [CustomerReference], 
H.DEL_REF [DeliveryReference], H.COMMENTS [HeaderComments], H.PAY_DATE [HeaderPaymentDate], H.TRANS_VAL [HeaderTransactionValue],
H.ANAL_M0 [HeaderAnalysisM0], 
(CASE WHEN H.ANAL_M0<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M0' AND ANAD_CODE=H.ANAL_M0) ELSE '''' END) [HeaderAnalysisM0Description], H.ANAL_M1 [HeaderAnalysisM1], 
(CASE WHEN H.ANAL_M1<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M1' AND ANAD_CODE=H.ANAL_M1) ELSE '''' END) [HeaderAnalysisM1Description], H.ANAL_M2 [HeaderAnalysisM2],
(CASE WHEN H.ANAL_M2<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M2' AND ANAD_CODE=H.ANAL_M2) ELSE '''' END) [HeaderAnalysisM2Description], H.ANAL_M3 [HeaderAnalysisM3],
(CASE WHEN H.ANAL_M3<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M3' AND ANAD_CODE=H.ANAL_M3) ELSE '''' END) [HeaderAnalysisM3Description], H.ANAL_M4 [HeaderAnalysisM4],
(CASE WHEN H.ANAL_M4<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M4' AND ANAD_CODE=H.ANAL_M4) ELSE '''' END) [HeaderAnalysisM4Description], H.ANAL_M5 [HeaderAnalysisM5],
(CASE WHEN H.ANAL_M5<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M5' AND ANAD_CODE=H.ANAL_M5) ELSE '''' END) [HeaderAnalysisM5Description], H.ANAL_M6 [HeaderAnalysisM6],
(CASE WHEN H.ANAL_M6<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M6' AND ANAD_CODE=H.ANAL_M6) ELSE '''' END) [HeaderAnalysisM6Description], H.ANAL_M7 [HeaderAnalysisM7],
(CASE WHEN H.ANAL_M7<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M7' AND ANAD_CODE=H.ANAL_M7) ELSE '''' END) [HeaderAnalysisM7Description], H.ANAL_M8 [HeaderAnalysisM8],
(CASE WHEN H.ANAL_M8<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M8' AND ANAD_CODE=H.ANAL_M8) ELSE '''' END) [HeaderAnalysisM8Description], H.ANAL_M9 [HeaderAnalysisM9],
(CASE WHEN H.ANAL_M9<>'''' THEN (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M9' AND ANAD_CODE=H.ANAL_M9) ELSE '''' END) [HeaderAnalysisM9Description], H.QUOTE_EXPIRY [HeaderQuotationExpiry],
H.QUOTED_PRD [HeaderQuotationPeriod], H.DATE_QUOTED [HeaderQuotationDate],H.QUOTE_CONVERT [HeaderQuotationStatus], H.CUST_CODE [CustomerCode], (SELECT ISNULL(ADD_LOOKUP,'')
FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE)[CustomerLookup],
(CASE WHEN CUST_CODE='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,1,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SICUS' AND CODE=H.TRANS_REF) ELSE (SELECT ADD_LINE_1 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerName],
(CASE WHEN CUST_CODE='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,51,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SICUS' AND CODE=H.TRANS_REF) ELSE (SELECT ADD_LINE_2 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerAddress1],
(CASE WHEN CUST_CODE='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,101,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SICUS' AND CODE=H.TRANS_REF) ELSE (SELECT ADD_LINE_3 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerAddress2],
(CASE WHEN CUST_CODE='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,151,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SICUS' AND CODE=H.TRANS_REF) ELSE (SELECT ADD_LINE_4 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerAddress3],
(CASE WHEN CUST_CODE='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,201,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SICUS' AND CODE=H.TRANS_REF) ELSE (SELECT ADD_LINE_5 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerAddress4],
(CASE WHEN CUST_CODE='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,251,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SICUS' AND CODE=H.TRANS_REF) ELSE (SELECT ADD_LINE_6 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerAddress5],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_TEL FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerTelephone],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_FAX FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerFax],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_EMAIL FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerEmail],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_WEB FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerWebPage],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_CONT FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerContact],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_COM_1 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerComment],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_COM_2 FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) [CustomerSecondComment],
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_LINE_1KH FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) CustomerNameKhmer,
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_LINE_2KH FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) CustomerAddress1Khmer,
(CASE WHEN CUST_CODE='''' THEN '''' ELSE (SELECT ADD_LINE_3KH FROM SIADD WHERE DB_CODE=@DB_CODE AND ADD_TYPE='0' AND ADD_CODE=CUST_CODE) END) CustomerAddress2Khmer,H.DELIV_ADD [DeliveryCode], 
(CASE WHEN DELIV_ADD='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,1,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SIDEL' AND CODE=H.TRANS_REF) ELSE (SELECT DEL_ADD_1 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryName], 
(CASE WHEN DELIV_ADD='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,51,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SIDEL' AND CODE=H.TRANS_REF) ELSE (SELECT DEL_ADD_2 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryAddress1], 
(CASE WHEN DELIV_ADD='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,101,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SIDEL' AND CODE=H.TRANS_REF) ELSE (SELECT DEL_ADD_3 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryAddress2],
(CASE WHEN DELIV_ADD='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,151,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SIDEL' AND CODE=H.TRANS_REF) ELSE (SELECT DEL_ADD_4 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryAddress3],
(CASE WHEN DELIV_ADD='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,201,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SIDEL' AND CODE=H.TRANS_REF) ELSE (SELECT DEL_ADD_5 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryAddress4],
(CASE WHEN DELIV_ADD='''' THEN (SELECT RTRIM(SUBSTRING(SI_DATA,251,50)) FROM SIDATA WHERE DB_CODE=@DB_CODE AND SI_TYPE='SIDEL' AND CODE=H.TRANS_REF) ELSE (SELECT DEL_ADD_6 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryAddress5],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_TEL FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryTelephone],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_FAX FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryFax],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_EMAIL FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryE-mail],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_WEB FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryWebPage],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_CONT FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryContact],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_COM_1 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliveryComment],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_COM_2 FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) [DeliverySecondComment],
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_ADD_1KH FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) DeliveryNameKhmer,
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_ADD_2KH FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) DeliveryAddress1Khmer,
(CASE WHEN DELIV_ADD='''' THEN '''' ELSE (SELECT DEL_ADD_3KH FROM SIDADD WHERE DB_CODE=@DB_CODE AND DEL_TYPE='0' AND DEL_CODE=DELIV_ADD AND ADD_CODE=CUST_CODE) END) DeliveryAddress2Khmer,
D.TRANS_LINE DetailLineNumber, D.DESCRIPTN [DetailDescription], D.DUE_DATE [DetailDueDate], D.VALUE_1, D.VALUE_2, D.VALUE_3, D.VALUE_4, D.VALUE_5, D.VALUE_6, D.VALUE_7, D.VALUE_8, D.VALUE_9,
D.VALUE_10, D.VALUE_11, D.VALUE_12, D.VALUE_13, D.VALUE_14, D.VALUE_15, D.VALUE_16, D.VALUE_17, D.VALUE_18, D.VALUE_19, D.VALUE_20,
(CASE D.SALE_QTY_VALUE WHEN 1 THEN D.VALUE_1 WHEN 2 THEN D.VALUE_2 WHEN 3 THEN D.VALUE_3 WHEN 4 THEN D.VALUE_4 WHEN 5 THEN D.VALUE_5 WHEN 6 THEN D.VALUE_6 WHEN 7 THEN D.VALUE_7 WHEN 8 THEN D.VALUE_8 WHEN 9 THEN D.VALUE_9 WHEN 10 THEN D.VALUE_10
WHEN 11 THEN D.VALUE_11 WHEN 12 THEN D.VALUE_12 WHEN 13 THEN D.VALUE_13 WHEN 14 THEN D.VALUE_14 WHEN 15 THEN D.VALUE_15 WHEN 16 THEN D.VALUE_16 WHEN 17 THEN D.VALUE_17 WHEN 18 THEN D.VALUE_18 WHEN 19 THEN D.VALUE_19 WHEN 20 THEN D.VALUE_20 ELSE 0 END) [SaleQuantity],
(CASE D.STK_QTY_VALUE WHEN 1 THEN D.VALUE_1 WHEN 2 THEN D.VALUE_2 WHEN 3 THEN D.VALUE_3 WHEN 4 THEN D.VALUE_4 WHEN 5 THEN D.VALUE_5 WHEN 6 THEN D.VALUE_6 WHEN 7 THEN D.VALUE_7 WHEN 8 THEN D.VALUE_8 WHEN 9 THEN D.VALUE_9 WHEN 10 THEN D.VALUE_10
WHEN 11 THEN D.VALUE_11 WHEN 12 THEN D.VALUE_12 WHEN 13 THEN D.VALUE_13 WHEN 14 THEN D.VALUE_14 WHEN 15 THEN D.VALUE_15 WHEN 16 THEN D.VALUE_16 WHEN 17 THEN D.VALUE_17 WHEN 18 THEN D.VALUE_18 WHEN 19 THEN D.VALUE_19 WHEN 20 THEN D.VALUE_20 ELSE 0 END) [StockQuantity],
(CASE D.TOT_VALUE WHEN 1 THEN D.VALUE_1 WHEN 2 THEN D.VALUE_2 WHEN 3 THEN D.VALUE_3 WHEN 4 THEN D.VALUE_4 WHEN 5 THEN D.VALUE_5 WHEN 6 THEN D.VALUE_6 WHEN 7 THEN D.VALUE_7 WHEN 8 THEN D.VALUE_8 WHEN 9 THEN D.VALUE_9 WHEN 10 THEN D.VALUE_10
WHEN 11 THEN D.VALUE_11 WHEN 12 THEN D.VALUE_12 WHEN 13 THEN D.VALUE_13 WHEN 14 THEN D.VALUE_14 WHEN 15 THEN D.VALUE_15 WHEN 16 THEN D.VALUE_16 WHEN 17 THEN D.VALUE_17 WHEN 18 THEN D.VALUE_18 WHEN 19 THEN D.VALUE_19 WHEN 20 THEN D.VALUE_20 ELSE 0 END) [TotalValue],
dbo.SI_REPORT_UNIT_VALUE(@DB_CODE,'',D.ITEM_CODE,(CASE D.STK_QTY_VALUE WHEN 1 THEN D.VALUE_1 WHEN 2 THEN D.VALUE_2 WHEN 3 THEN D.VALUE_3 WHEN 4 THEN D.VALUE_4 WHEN 5 THEN D.VALUE_5 WHEN 6 THEN D.VALUE_6 WHEN 7 THEN D.VALUE_7 WHEN 8 THEN D.VALUE_8 WHEN 9 THEN D.VALUE_9 WHEN 10 THEN D.VALUE_10
WHEN 11 THEN D.VALUE_11 WHEN 12 THEN D.VALUE_12 WHEN 13 THEN D.VALUE_13 WHEN 14 THEN D.VALUE_14 WHEN 15 THEN D.VALUE_15 WHEN 16 THEN D.VALUE_16 WHEN 17 THEN D.VALUE_17 WHEN 18 THEN D.VALUE_18 WHEN 19 THEN D.VALUE_19 WHEN 20 THEN D.VALUE_20 ELSE 0 END)) [ReportConvertStockQuantity],
dbo.SI_REPORT_UNIT(@DB_CODE,'',D.ITEM_CODE) [ReportConvertUnit], D.DEL_DATE AS [DetailDeliveryDate], D.ACCNT_CODE [DetailAccountCode], D.UNIT_SALE [DetailUnitofSale],
(CASE WHEN D.UNIT_SALE<>'' THEN (SELECT CONV_F_DESC FROM SIUNITCONV WHERE DB_CODE=@DB_CODE AND CONV_FROM=D.UNIT_SALE) ELSE '' END) [UnitOfSaleDescription],
(CASE WHEN D.UNIT_SALE<>'' THEN (SELECT FACTOR FROM SIUNITCONV WHERE DB_CODE=@DB_CODE AND CONV_FROM=D.UNIT_SALE) ELSE 0 END) [UnitOfSaleFactor],
(SELECT ISNULL(SUM(TOTAL),0) FROM {dto.DbCode}SIINVMOV WHERE MOV_REF=H.TRANS_REF AND ORIG_LINE_NO=D.TRANS_LINE) [CostValue], D.ANAL_M0 [DetailAnalysisM0],
(CASE WHEN D.ANAL_M0='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M0' AND ANAD_CODE=D.ANAL_M0) END) [DetailAnalysisM0Description], D.ANAL_M1 [DetailAnalysisM1],
(CASE WHEN D.ANAL_M1='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M1' AND ANAD_CODE=D.ANAL_M1) END) [DetailAnalysisM1Description], D.ANAL_M2 [DetailAnalysisM2],
(CASE WHEN D.ANAL_M2='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M2' AND ANAD_CODE=D.ANAL_M2) END) [DetailAnalysisM2Description], D.ANAL_M3 [DetailAnalysisM3],
(CASE WHEN D.ANAL_M3='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M3' AND ANAD_CODE=D.ANAL_M3) END) [DetailAnalysisM3Description], D.ANAL_M4 [DetailAnalysisM4],
(CASE WHEN D.ANAL_M4='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M4' AND ANAD_CODE=D.ANAL_M4) END) [DetailAnalysisM4Description], D.ANAL_M5 [DetailAnalysisM5],
(CASE WHEN D.ANAL_M5='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M5' AND ANAD_CODE=D.ANAL_M5) END) [DetailAnalysisM5Description], D.ANAL_M6 [DetailAnalysisM6],
(CASE WHEN D.ANAL_M6='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M6' AND ANAD_CODE=D.ANAL_M6) END) [DetailAnalysisM6Description], D.ANAL_M7 [DetailAnalysisM7],
(CASE WHEN D.ANAL_M7='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M7' AND ANAD_CODE=D.ANAL_M7) END) [DetailAnalysisM7Description], D.ANAL_M8 [DetailAnalysisM8],
(CASE WHEN D.ANAL_M8='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M8' AND ANAD_CODE=D.ANAL_M8) END) [DetailAnalysisM8Description], D.ANAL_M9 [DetailAnalysisM9],
(CASE WHEN D.ANAL_M9='''' THEN '''' ELSE (SELECT ANAD_DESC FROM SIANALD WHERE DB_CODE=@DB_CODE AND ANAM_CODE='M9' AND ANAD_CODE=D.ANAL_M9) END) [DetailAnalysisM9Description], D.LINE_REF [DetailLineReference],
D.ITEM_CODE [DetailItemCode], (CASE WHEN D.ITEM_CODE='' THEN '' ELSE (SELECT ITEM_BCODE FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemBarCode],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_DESC FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemDescription],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_LOOKUP FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemLookup],
(CASE WHEN D.ITEM_CODE='''' THEN 0 ELSE (SELECT ITEM_PRICE1 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemPrice1],
(CASE WHEN D.ITEM_CODE='''' THEN 0 ELSE (SELECT ITEM_PRICE2 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemPrice2],
(CASE WHEN D.ITEM_CODE='''' THEN 0 ELSE (SELECT ITEM_PRICE3 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemPrice3],
(CASE WHEN D.ITEM_CODE='''' THEN 0 ELSE (SELECT ITEM_PRICE4 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemPrice4],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_LEVEL FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemLevel], 
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_TYPE FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemType],
(CASE WHEN D.ITEM_CODE='''' THEN 0 ELSE (SELECT ITEM_DCOST FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCost],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT UNIT_STOCK FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemUnitOfStock],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT UNIT_SALE FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemUnitOfSale],
(CASE WHEN D.ITEM_CODE='''' THEN 0 ELSE (SELECT UNIT_WEIGHT FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemUnitOfWeight],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT UPDT_PRICE FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemUpdatePrice],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS1 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom1],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS2 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom2],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS3 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom3],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS4 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom4],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS5 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom5],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS6 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom6],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS7 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom7],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS8 FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) [ItemCustom8],
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS9_KH FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) ItemCustom9Khmer,
(CASE WHEN D.ITEM_CODE='''' THEN '''' ELSE (SELECT ITEM_CUS10_KH FROM SIITEMS WHERE DB_CODE=@DB_CODE AND ITEM_CODE=D.ITEM_CODE) END) ItemCustom10Khmer,
D.LOCATION [Detail Location Code], (CASE WHEN D.LOCATION='' THEN '' ELSE (SELECT WAR_NAME FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationName],
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_ADD1 FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationAddress1],
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_ADD2 FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationAddress2],
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_ADD3 FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationAddress3],
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_TEL1 FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationTelephone1],
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_TEL2 FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationTelephone2],
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_FAX FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationFax], 
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_COM1 FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationComment],
(CASE WHEN D.LOCATION='''' THEN '''' ELSE (SELECT WAR_COM2 FROM SIWAREH WHERE DB_CODE=@DB_CODE AND WAR_CODE=D.LOCATION) END) [LocationSecondComment] 
FROM  {dto.DbCode}SISOHDR H INNER JOIN {dto.DbCode}SISODET D ON  D.TRANS_REF = H.TRANS_REF WHERE H.VOID_STATUS=@VOID_STATUS AND H.REC_TYPE=@HEADER_REC_TYPE  AND D.INV_PRD=0  AND D.REC_TYPE=@DETAIL_REC_TYPE"+conditionByDate+condition;
            var param = new
            {
                DB_CODE = dto.DbCode,
                VOID_STATUS = dto.VoidStatus,
                HEADER_REC_TYPE = dto.HeaderRecType,
                DETAIL_REC_TYPE = dto.DetailRecType,
                PRD_1 = dto.Prd1,
                PRD_2 = dto.Prd2,
                Code1 = dto.Code1,
                Code2 = dto.Code2,
                Loc1 = dto.Loc1,
                Loc2 = dto.Loc2,
                Item1 = dto.Item1,
                Item2 = dto.Item2,
                Ref1 = dto.Ref1,
                Ref2 = dto.Ref2,
                Date1 = dto.Date1,
                Date2 = dto.Date2,
                ANAL_M3 = dto.AnalM3
            };
            var execute = await _sqlDataAccess.LoadData<SaleListingModel, dynamic>(sql, param);
            return execute.ToList();
        }
    }
}
